version: '3'
services:
  shinobi-sql:
    image: mariadb:10.6.22-jammy
    volumes:
      - /DATA/AppData/shinobidocker-shinobi-sql-1/data:/var/lib/mysql
      - /DATA/AppData/shinobidocker-shinobi-sql-1/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=ccio
      - MARIADB_USER=majesticflame
      - MARIADB_PASSWORD=1234
    restart: unless-stopped
